### ISSUE TITLE
Thoughts on astar?

### ISSUE THREAD

**Issue by siler** [bonsairobo/building-blocks#20]
Hello! I've really been enjoying using this library so far. Was looking at the pathfinding algorithms and noticed building-blocks doesn't have astar yet. Is that something you're interested in including? If so, I'd be open to working on integrating it from `pathfinding`.

**Comment by bonsairobo** [comment]
@siler Thanks for bringing this up! I would love to include A*. The only reason it's not already included is because it was too slow for my particular use case, and I replaced it with a greedy best-first search, but I'm sure I will need A* again at some point.

I've actually used the pathfinding crate to do this before, so it should be straightforward to integrate. If you want to submit a PR, that would be welcome.

**Comment by bonsairobo** [comment]
Thanks for the PR!

**Comment by siler** [comment]
Yep, thanks for the fantastic library. :)
